In [1]:
import sys
import os
import pandas as pd

# Add the absolute path to the scripts folder
scripts_path = os.path.abspath("../scripts")
sys.path.append(scripts_path)

# Now import directly from the file
from data_prep import (
    clean_column_names,
    encode_target,
    split_features,
    create_actionable_df,
    remove_duplicates,
    add_age_group,
    add_housing_loan_interaction,
    impute_marital_unknown,
    transform_pdays,
    get_features_to_keep,  split_features_target,
    get_column_types,
    build_preprocessor,
    time_based_split,
    preprocess_data, 
    remove_outliers_iqr

)

from utils import save_processed_splits

In [88]:
df = pd.read_csv(r'C:\Users\DELL\OneDrive\Data Science\Bank_Telemarketing_Prediction_EDSB25_1\data\raw\bank-additional-full.csv', sep=';')
print(df.columns.tolist())

['age', 'job', 'marital', 'education', 'default', 'housing', 'loan', 'contact', 'month', 'day_of_week', 'duration', 'campaign', 'pdays', 'previous', 'poutcome', 'emp.var.rate', 'cons.price.idx', 'cons.conf.idx', 'euribor3m', 'nr.employed', 'y']

In [89]:
df

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,57,services,married,high.school,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,37,services,married,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,40,admin.,married,basic.6y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,56,services,married,high.school,no,no,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41183,73,retired,married,professional.course,no,yes,no,cellular,nov,fri,...,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,yes
41184,46,blue-collar,married,professional.course,no,no,no,cellular,nov,fri,...,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no
41185,56,retired,married,university.degree,no,yes,no,cellular,nov,fri,...,2,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no
41186,44,technician,married,professional.course,no,no,no,cellular,nov,fri,...,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,yes
41187,74,retired,married,professional.course,no,yes,no,cellular,nov,fri,...,3,999,1,failure,-1.1,94.767,-50.8,1.028,4963.6,no

In [90]:
# Load raw data
df = pd.read_csv(
    r'C:\Users\DELL\OneDrive\Data Science\Bank_Telemarketing_Prediction_EDSB25_1\data\raw\bank-additional-full.csv',
    sep=';'
)
# Preprocessing
df = clean_column_names(df)
df = encode_target(df, target_col="y")

# Split features
X_act, X_bmk, y = split_features(df)

# Create actionable dataframe
df_act = create_actionable_df(X_act, y)

# Check results
print(df_act.shape)
df_act.head()

(39404, 20)

,job,marital,education,default,housing,loan,contact,month,day_of_week,poutcome,age,campaign,pdays,previous,emp_var_rate,cons_price_idx,cons_conf_idx,euribor3m,nr_employed,y
0,housemaid,married,basic.4y,no,no,no,telephone,may,mon,nonexistent,56,1,999,0,1.1,93.994,-36.4,4.857,5191.0,0
1,services,married,high.school,unknown,no,no,telephone,may,mon,nonexistent,57,1,999,0,1.1,93.994,-36.4,4.857,5191.0,0
2,services,married,high.school,no,yes,no,telephone,may,mon,nonexistent,37,1,999,0,1.1,93.994,-36.4,4.857,5191.0,0
3,admin.,married,basic.6y,no,no,no,telephone,may,mon,nonexistent,40,1,999,0,1.1,93.994,-36.4,4.857,5191.0,0
4,services,married,high.school,no,no,yes,telephone,may,mon,nonexistent,56,1,999,0,1.1,93.994,-36.4,4.857,5191.0,0

In [91]:
import data_prep as dp
print(dir(dp))

['ColumnTransformer', 'OneHotEncoder', 'StandardScaler', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'add_age_group', 'add_housing_loan_interaction', 'build_preprocessor', 'clean_column_names', 'create_actionable_df', 'encode_target', 'get_column_types', 'get_features_to_keep', 'impute_marital_unknown', 'np', 'pd', 'preprocess_data', 'remove_duplicates', 'remove_outliers_iqr', 'split_features', 'split_features_target', 'time_based_split', 'transform_pdays']

In [92]:
remove_duplicates(df_act)

Duplicates removed: 0

,job,marital,education,default,housing,loan,contact,month,day_of_week,poutcome,age,campaign,pdays,previous,emp_var_rate,cons_price_idx,cons_conf_idx,euribor3m,nr_employed,y
0,housemaid,married,basic.4y,no,no,no,telephone,may,mon,nonexistent,56,1,999,0,1.1,93.994,-36.4,4.857,5191.0,0
1,services,married,high.school,unknown,no,no,telephone,may,mon,nonexistent,57,1,999,0,1.1,93.994,-36.4,4.857,5191.0,0
2,services,married,high.school,no,yes,no,telephone,may,mon,nonexistent,37,1,999,0,1.1,93.994,-36.4,4.857,5191.0,0
3,admin.,married,basic.6y,no,no,no,telephone,may,mon,nonexistent,40,1,999,0,1.1,93.994,-36.4,4.857,5191.0,0
4,services,married,high.school,no,no,yes,telephone,may,mon,nonexistent,56,1,999,0,1.1,93.994,-36.4,4.857,5191.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41183,retired,married,professional.course,no,yes,no,cellular,nov,fri,nonexistent,73,1,999,0,-1.1,94.767,-50.8,1.028,4963.6,1
41184,blue-collar,married,professional.course,no,no,no,cellular,nov,fri,nonexistent,46,1,999,0,-1.1,94.767,-50.8,1.028,4963.6,0
41185,retired,married,university.degree,no,yes,no,cellular,nov,fri,nonexistent,56,2,999,0,-1.1,94.767,-50.8,1.028,4963.6,0
41186,technician,married,professional.course,no,no,no,cellular,nov,fri,nonexistent,44,1,999,0,-1.1,94.767,-50.8,1.028,4963.6,1
41187,retired,married,professional.course,no,yes,no,cellular,nov,fri,failure,74,3,999,1,-1.1,94.767,-50.8,1.028,4963.6,0

In [93]:
df_act = remove_outliers_iqr(df_act, 'campaign')
df_act = remove_outliers_iqr(df_act, 'age')
df_act = remove_outliers_iqr(df_act, 'cons_conf_idx')

campaign: Removed 691 outliers
age: Removed 2 outliers
cons_conf_idx: Removed 0 outliers

In [94]:
df_act["age"].describe()

count    38711.000000
mean        40.102297
std         10.464800
min         17.000000
25%         32.000000
50%         38.000000
75%         47.000000
max         95.000000
Name: age, dtype: float64

In [95]:
add_age_group(df_act)

,job,marital,education,default,housing,loan,contact,month,day_of_week,poutcome,...,campaign,pdays,previous,emp_var_rate,cons_price_idx,cons_conf_idx,euribor3m,nr_employed,y,age_group
0,housemaid,married,basic.4y,no,no,no,telephone,may,mon,nonexistent,...,1,999,0,1.1,93.994,-36.4,4.857,5191.0,0,senior
1,services,married,high.school,unknown,no,no,telephone,may,mon,nonexistent,...,1,999,0,1.1,93.994,-36.4,4.857,5191.0,0,senior
2,services,married,high.school,no,yes,no,telephone,may,mon,nonexistent,...,1,999,0,1.1,93.994,-36.4,4.857,5191.0,0,adult
3,admin.,married,basic.6y,no,no,no,telephone,may,mon,nonexistent,...,1,999,0,1.1,93.994,-36.4,4.857,5191.0,0,adult
4,services,married,high.school,no,no,yes,telephone,may,mon,nonexistent,...,1,999,0,1.1,93.994,-36.4,4.857,5191.0,0,senior
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41183,retired,married,professional.course,no,yes,no,cellular,nov,fri,nonexistent,...,1,999,0,-1.1,94.767,-50.8,1.028,4963.6,1,senior
41184,blue-collar,married,professional.course,no,no,no,cellular,nov,fri,nonexistent,...,1,999,0,-1.1,94.767,-50.8,1.028,4963.6,0,adult
41185,retired,married,university.degree,no,yes,no,cellular,nov,fri,nonexistent,...,2,999,0,-1.1,94.767,-50.8,1.028,4963.6,0,senior
41186,technician,married,professional.course,no,no,no,cellular,nov,fri,nonexistent,...,1,999,0,-1.1,94.767,-50.8,1.028,4963.6,1,adult
41187,retired,married,professional.course,no,yes,no,cellular,nov,fri,failure,...,3,999,1,-1.1,94.767,-50.8,1.028,4963.6,0,senior

In [96]:
add_housing_loan_interaction(df_act)

,job,marital,education,default,housing,loan,contact,month,day_of_week,poutcome,...,pdays,previous,emp_var_rate,cons_price_idx,cons_conf_idx,euribor3m,nr_employed,y,age_group,housing_loan_interaction
0,housemaid,married,basic.4y,no,no,no,telephone,may,mon,nonexistent,...,999,0,1.1,93.994,-36.4,4.857,5191.0,0,senior,no_no
1,services,married,high.school,unknown,no,no,telephone,may,mon,nonexistent,...,999,0,1.1,93.994,-36.4,4.857,5191.0,0,senior,no_no
2,services,married,high.school,no,yes,no,telephone,may,mon,nonexistent,...,999,0,1.1,93.994,-36.4,4.857,5191.0,0,adult,yes_no
3,admin.,married,basic.6y,no,no,no,telephone,may,mon,nonexistent,...,999,0,1.1,93.994,-36.4,4.857,5191.0,0,adult,no_no
4,services,married,high.school,no,no,yes,telephone,may,mon,nonexistent,...,999,0,1.1,93.994,-36.4,4.857,5191.0,0,senior,no_yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41183,retired,married,professional.course,no,yes,no,cellular,nov,fri,nonexistent,...,999,0,-1.1,94.767,-50.8,1.028,4963.6,1,senior,yes_no
41184,blue-collar,married,professional.course,no,no,no,cellular,nov,fri,nonexistent,...,999,0,-1.1,94.767,-50.8,1.028,4963.6,0,adult,no_no
41185,retired,married,university.degree,no,yes,no,cellular,nov,fri,nonexistent,...,999,0,-1.1,94.767,-50.8,1.028,4963.6,0,senior,yes_no
41186,technician,married,professional.course,no,no,no,cellular,nov,fri,nonexistent,...,999,0,-1.1,94.767,-50.8,1.028,4963.6,1,adult,no_no
41187,retired,married,professional.course,no,yes,no,cellular,nov,fri,failure,...,999,1,-1.1,94.767,-50.8,1.028,4963.6,0,senior,yes_no

In [97]:
impute_marital_unknown(df_act)

,job,marital,education,default,housing,loan,contact,month,day_of_week,poutcome,...,pdays,previous,emp_var_rate,cons_price_idx,cons_conf_idx,euribor3m,nr_employed,y,age_group,housing_loan_interaction
0,housemaid,married,basic.4y,no,no,no,telephone,may,mon,nonexistent,...,999,0,1.1,93.994,-36.4,4.857,5191.0,0,senior,no_no
1,services,married,high.school,unknown,no,no,telephone,may,mon,nonexistent,...,999,0,1.1,93.994,-36.4,4.857,5191.0,0,senior,no_no
2,services,married,high.school,no,yes,no,telephone,may,mon,nonexistent,...,999,0,1.1,93.994,-36.4,4.857,5191.0,0,adult,yes_no
3,admin.,married,basic.6y,no,no,no,telephone,may,mon,nonexistent,...,999,0,1.1,93.994,-36.4,4.857,5191.0,0,adult,no_no
4,services,married,high.school,no,no,yes,telephone,may,mon,nonexistent,...,999,0,1.1,93.994,-36.4,4.857,5191.0,0,senior,no_yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41183,retired,married,professional.course,no,yes,no,cellular,nov,fri,nonexistent,...,999,0,-1.1,94.767,-50.8,1.028,4963.6,1,senior,yes_no
41184,blue-collar,married,professional.course,no,no,no,cellular,nov,fri,nonexistent,...,999,0,-1.1,94.767,-50.8,1.028,4963.6,0,adult,no_no
41185,retired,married,university.degree,no,yes,no,cellular,nov,fri,nonexistent,...,999,0,-1.1,94.767,-50.8,1.028,4963.6,0,senior,yes_no
41186,technician,married,professional.course,no,no,no,cellular,nov,fri,nonexistent,...,999,0,-1.1,94.767,-50.8,1.028,4963.6,1,adult,no_no
41187,retired,married,professional.course,no,yes,no,cellular,nov,fri,failure,...,999,1,-1.1,94.767,-50.8,1.028,4963.6,0,senior,yes_no

In [98]:
transform_pdays(df_act)

,job,marital,education,default,housing,loan,contact,month,day_of_week,poutcome,...,previous,emp_var_rate,cons_price_idx,cons_conf_idx,euribor3m,nr_employed,y,age_group,housing_loan_interaction,pdays_cat
0,housemaid,married,basic.4y,no,no,no,telephone,may,mon,nonexistent,...,0,1.1,93.994,-36.4,4.857,5191.0,0,senior,no_no,never_contacted
1,services,married,high.school,unknown,no,no,telephone,may,mon,nonexistent,...,0,1.1,93.994,-36.4,4.857,5191.0,0,senior,no_no,never_contacted
2,services,married,high.school,no,yes,no,telephone,may,mon,nonexistent,...,0,1.1,93.994,-36.4,4.857,5191.0,0,adult,yes_no,never_contacted
3,admin.,married,basic.6y,no,no,no,telephone,may,mon,nonexistent,...,0,1.1,93.994,-36.4,4.857,5191.0,0,adult,no_no,never_contacted
4,services,married,high.school,no,no,yes,telephone,may,mon,nonexistent,...,0,1.1,93.994,-36.4,4.857,5191.0,0,senior,no_yes,never_contacted
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41183,retired,married,professional.course,no,yes,no,cellular,nov,fri,nonexistent,...,0,-1.1,94.767,-50.8,1.028,4963.6,1,senior,yes_no,never_contacted
41184,blue-collar,married,professional.course,no,no,no,cellular,nov,fri,nonexistent,...,0,-1.1,94.767,-50.8,1.028,4963.6,0,adult,no_no,never_contacted
41185,retired,married,university.degree,no,yes,no,cellular,nov,fri,nonexistent,...,0,-1.1,94.767,-50.8,1.028,4963.6,0,senior,yes_no,never_contacted
41186,technician,married,professional.course,no,no,no,cellular,nov,fri,nonexistent,...,0,-1.1,94.767,-50.8,1.028,4963.6,1,adult,no_no,never_contacted
41187,retired,married,professional.course,no,yes,no,cellular,nov,fri,failure,...,1,-1.1,94.767,-50.8,1.028,4963.6,0,senior,yes_no,never_contacted

In [99]:
# Feature engineering

features_to_keep = get_features_to_keep(df_act)
print("Features to keep:", features_to_keep)

Features to keep: ['job', 'marital', 'education', 'housing', 'loan', 'contact', 'month', 'day_of_week', 'poutcome', 'age', 'campaign', 'pdays', 'previous', 'emp_var_rate', 'cons_price_idx', 'cons_conf_idx', 'euribor3m', 'nr_employed', 'age_group', 'housing_loan_interaction', 'pdays_cat']

In [100]:
df_clean = df_act.drop(columns=['nr_employed',"campaign", 'previous','poutcome','pdays_cat', 'cons_price_idx',"euribor3m","default"]).copy()

#df_clean = df_act.drop(columns=['nr_employed',"default",'campaign', 'previous','poutcome','pdays_cat', 'cons_conf_idx',"emp_var_rate","nr_employed"]).copy()

In [101]:
# 1. Split features and target
X, y = split_features_target(df_clean, target_col="y")

# 2. Identify column types
numerical_cols, categorical_cols = get_column_types(X)

In [102]:
# 3. Build preprocessor
preprocessor = build_preprocessor(numerical_cols, categorical_cols)

# 4. Time-based split
X_train, X_test, y_train, y_test = time_based_split(X, y, train_ratio=0.8)

X_test_unprocessed=X_test.copy()


# 5. Fit and transform
X_train_processed, X_test_processed = preprocess_data(X_train, X_test, preprocessor)
print("Train shape:", X_train_processed.shape, y_train.shape)
print("Test shape:", X_test_processed.shape, y_test.shape)

Train shape: (30968, 58) (30968,)
Test shape: (7743, 58) (7743,)

In [103]:


save_processed_splits(
    X_train_processed,   # shape (30968, 61)
    y_train,             # shape (30968,)
    X_test_processed,    # shape (7743, 61)
    y_test,              # shape (7743,)
    preprocessor,
    r"C:\Users\DELL\OneDrive\Data Science\Bank_Telemarketing_Prediction_EDSB25_1\data\processed"
)

Processed splits saved to C:\Users\DELL\OneDrive\Data Science\Bank_Telemarketing_Prediction_EDSB25_1\data\processed

In [104]:
print("X_train_processed shape:", X_train_processed.shape)
print("X_test_processed shape:", X_test_processed.shape)
print("Feature names length:", len(preprocessor.get_feature_names_out()))

X_train_processed shape: (30968, 58)
X_test_processed shape: (7743, 58)
Feature names length: 58

In [105]:
# Save X_test_unprocessed into data/processed folder
X_test_unprocessed.to_csv("../data/interim/test_unprocessed.csv", index=False)

print("✅ Saved X_test_unprocessed to data/interim/test_unprocessed.csv")

✅ Saved X_test_unprocessed to data/interim/test_unprocessed.csv

In [106]:
X_test_processed

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 107839 stored elements and shape (7743, 58)>